name: arb_merge
description: A command-line tool to merge ARB files from multiple sources based on the files' locale.
version: 1.0.1
homepage: https://abcx3.com
topics: [tools, arb, internationalization, merge]
repository: https://github.com/FredrikBorgstrom/arb_merge

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  args: ^2.5.0
  logging: ^1.2.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.25.8
  coverage: ^1.9.0
  flutter_lints: ^4.0.0
arb_merge:
  sources: example/primarySource,example/secondarySource
  destination: example/merged
  sort: false
  pattern: 'intl_{lang}.arb'
  verbose: false

